language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy releases'
    if: tag IS present
script:
  - make test
jobs:
  include:
    - stage: 'deploy pages'
      before_deploy: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        on:
          branch: master
    - stage: 'deploy releases'
      before_deploy:
        - sed -i -e "s/SHA/$TRAVIS_TAG/g" index.html
        - echo '# Release Notes' > BODY.md
        - echo "" >> BODY.md
        - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
            echo "See [Changelog](https://github.com/deild/travisci/commits/$TRAVIS_TAG)" >> BODY.md;
          else
            echo "See [Changelog](https://github.com/deild/travisci/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)" >> BODY.md;
          fi
        - export BODY="$(<BODY.md)"
        - curl -fLo "$HOME/bin/ghr.tar.gz" --create-dirs https://github.com/tcnksm/ghr/releases/download/v0.12.2/ghr_v0.12.2_linux_amd64.tar.gz
        - tar -xvzf $HOME/bin/ghr.tar.gz -C $HOME/bin
        - $HOME/bin/ghr_v0.12.2_linux_amd64/ghr -version
        - mkdir -p upload
        - tar -czf upload/www.tar.xz index.html
        - sha256sum upload/www.tar.xz > upload/www.tar.xz.sha256
      deploy:
        provider: scripts
        skip_cleanup: true
        overwrite: true
        script: $HOME/bin/ghr_v0.12.2_linux_amd64/ghr -b "$BODY" -replace $TRAVIS_TAG upload/
        on:
          repo: deild/travisci
          tags: true
