language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy releases'
    if: tag IS present
script:
  - make test
jobs:
  include:
    - stage: 'deploy pages'
      before_deploy: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        on:
          branch: master
    - stage: 'deploy releases'
      before_deploy:
        - sed -i -e "s/SHA/$TRAVIS_TAG/g" index.html
        - echo '# Release Notes' > BODY.md
        - echo "" >> BODY.md
        - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
            echo "See [Changelog](https://github.com/deild/travisci/commits/$TRAVIS_TAG)" >> BODY.md;
          else
            echo "See [Changelog](https://github.com/deild/travisci/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)" >> BODY.md;
          fi
        - curl -fLo "$HOME/bin/gothub.bz2" --create-dirs https://github.com/deild/gothub/releases/download/v0.8.0/linux-amd64-gothub.bz2
        - bunzip2 $HOME/bin/gothub.bz2
        - chmod +x $HOME/bin/gothub
        - $HOME/bin/gothub --version
        - tar -czf www.tar.xz index.html
        - sha256sum www.tar.xz > www.tar.xz.sha256
      deploy:
        provider: scripts
        skip_cleanup: true
        overwrite: true
        script:
          - $HOME/bin/gothub release -u deild -r travisci -t $TRAVIS_TAG -n $TRAVIS_TAG -d - < BODY.md
          - $HOME/bin/gothub upload -u deild -r travisci -t $TRAVIS_TAG -n "www.tar.xz" -f www.tar.xz -R
          - $HOME/bin/gothub upload -u deild -r travisci -t $TRAVIS_TAG -n "www.tar.xz.sha256" -f www.tar.xz.sha256 -R
        on:
          repo: deild/travisci
          tags: true
