language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy release'
    if: tag IS present
jobs:
  include:
    - stage: 'deploy pages'
      script: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        on:
          branch: master
    - stage: 'deploy release'
      install: echo "[$TRAVIS_BUILD_STAGE_NAME:install]"
      script: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "index.html"
        skip_cleanup: true
        on:
          tags: true
before_install: echo "[before_install]"
install: echo "[install]"
before_script: echo "[before_script]"
script:
  - echo "[$TRAVIS_BUILD_STAGE_NAME]"
  - make test
after_success: echo "[after_success]"
after_failure: echo "[after_failure]"
before_deploy: echo "[before_deploy]"
deploy:
  provider: script
  script: echo "[deploy]"
after_deploy: echo "[after_deploy]"
after_script: echo "[after_script]"
