language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy release'
    if: tag IS present
jobs:
  include:
    - stage: 'deploy pages'
      script: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        on:
          branch: master
    - stage: 'deploy release'
      before_deploy:
        - sed -i -e "s/SHA/$TRAVIS_TAG/g" index.html
        - export LATEST=$(git tag -l v[0-9].* | tail -n2 | head -n1)
        - if [[ -z $LATEST ]]; then
            export BODY="https://github.com/deild/travisci/commits/$TRAVIS_TAG";
          else
            export BODY="https://github.com/deild/travisci/compare/$LATEST...$TRAVIS_TAG";
          fi
        - tar -czf www.tar.xz index.html
        - sha256sum www.tar.xz > www.tar.xz.sha256
      deploy:
        provider: releases
        overwrite: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - "*.tar.xz"
          - "*.sha256"
        skip_cleanup: true
        body: $BODY
        on:
          repo: deild/travisci
          tags: true
script:
  - make test