language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy releases'
    if: tag IS present
script:
  - make test
jobs:
  include:
    - stage: 'deploy pages'
      before_deploy: sed -i -e "s/SHA/$TRAVIS_COMMIT/g" index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        on:
          branch: master
    - stage: 'deploy releases'
      before_deploy:
        - sed -i -e "s/SHA/$TRAVIS_TAG/g" index.html
        - printf '# Release Notes\n\n' > BODY.md
        - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
            echo "See [Changelog](https://github.com/deild/travisci/commits/$TRAVIS_TAG)" >> BODY.md;
          else
            echo "See [Changelog](https://github.com/deild/travisci/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)" >> BODY.md;
          fi
        - export BODY=$(<BODY.md)
        - tar -czf www.tar.xz index.html
        - sha256sum www.tar.xz > www.tar.xz.sha256
      deploy:
        provider: releases
        overwrite: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - "*.tar.xz"
          - "*.sha256"
        skip_cleanup: true
        body: $BODY
        on:
          repo: deild/travisci
          tags: true
