language: minimal
env:
 - FOO=one
 - FOO=two
before_install: echo "[before_install]"
install: echo "[install]"
before_script: echo "[before_script]"
script: echo "[$TRAVIS_BUILD_STAGE_NAME]"
after_success: echo "[after_success]"
after_failure: echo "[after_failure]"
before_deploy: echo "[before_deploy]"
deploy:
  provider: script
  script: echo "[deploy]"
after_deploy: echo "[after_deploy]"
after_script: echo "[after_script]"
